In [3]:
import pandas as pd
import numpy as np

# display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)

In [4]:
df = pd.read_csv("../data/raw/amazon-reviews-org.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (72500, 9)

,reviewId,reviewDate,mainDepartment,subDepartment,productName,reviewTitle,reviewStar,reviewText,inconsistentStatus
0,R1TWIP923TUPRV,"Reviewed in the United States on August 8, 2021",Beauty and Personal Care,"Foot,Hand & Nail Care","Hard As Hoof Nail Strengthening Cream with Coconut Scent Nail Strengthener, Nail Growth & Conditioning Cuticle Cream Stops Splits, Chips, Cracks & Strengthens Nails, 1 oz",Didn't work,1.0,No change in nails at all.,0
1,R1N5I12682L3YY,"Reviewed in the United States on August 2, 2021",Beauty and Personal Care,"Foot,Hand & Nail Care","Hard As Hoof Nail Strengthening Cream with Coconut Scent Nail Strengthener, Nail Growth & Conditioning Cuticle Cream Stops Splits, Chips, Cracks & Strengthens Nails, 1 oz",Worst nail product I have ever used.,1.0,Garbage! Do not waste your $$$. My nails were worse after using this product for two weeks. Pathetic! Going back to my Vaseline Healthy Hand and and Nails.,1
2,R1S3UGVIPYX6W5,"Reviewed in the United States on July 27, 2021",Beauty and Personal Care,"Foot,Hand & Nail Care","Hard As Hoof Nail Strengthening Cream with Coconut Scent Nail Strengthener, Nail Growth & Conditioning Cuticle Cream Stops Splits, Chips, Cracks & Strengthens Nails, 1 oz",Just didn't work,1.0,Nails are still brittle,1
3,R3RELGNNBTGZ2V,"Reviewed in the United States on July 26, 2021",Beauty and Personal Care,"Foot,Hand & Nail Care","Hard As Hoof Nail Strengthening Cream with Coconut Scent Nail Strengthener, Nail Growth & Conditioning Cuticle Cream Stops Splits, Chips, Cracks & Strengthens Nails, 1 oz",Scum,1.0,Didn’t do any improvement at all.,0
4,RLQ9C5R2KYV67,"Reviewed in the United States on July 24, 2021",Beauty and Personal Care,"Foot,Hand & Nail Care","Hard As Hoof Nail Strengthening Cream with Coconut Scent Nail Strengthener, Nail Growth & Conditioning Cuticle Cream Stops Splits, Chips, Cracks & Strengthens Nails, 1 oz",Okay for cuticles,1.0,"Helped cuticles, didn't do much for my nails. I gave this product a decent time line, two jars, six months. Nails didn't improve.",0

In [5]:
df = df.dropna(subset=["reviewText"])

In [6]:
def create_binary_sentiment(star):
    if star <= 2:
        return 0   # negative
    elif star >= 4:
        return 1   # positive
    else:
        return None  # neutral (3-star)

In [7]:
df["sentiment"] = df["reviewStar"].apply(create_binary_sentiment)

In [8]:
df = df.dropna(subset=["sentiment"])

In [9]:
before = len(df)
df_filtered = df[df["reviewText"].str.len() > 20]
after = len(df_filtered)

print("Removed:", before - after)
print("Remaining:", after)

Removed: 4629
Remaining: 53365

In [10]:
import sys
import os
import nltk

sys.path.append(os.path.abspath(".."))
print(os.getcwd())

c:\Users\USER\Desktop\FYP\fyp-nlp-reviews\notebooks

In [12]:
from importlib import reload
import src.data.preprocess as p
reload(p)
from src.data.preprocess import preprocess_text
import contractions

df["clean_text"] = df["reviewText"].apply(preprocess_text)
df[["reviewText", "clean_text"]].head()

,reviewText,clean_text
0,No change in nails at all.,no change nails
1,Garbage! Do not waste your $$$. My nails were worse after using this product for two weeks. Pathetic! Going back to my Vaseline Healthy Hand and and Nails.,garbage not waste nails worse using product two weeks pathetic going back vaseline healthy hand nails
2,Nails are still brittle,nails still brittle
3,Didn’t do any improvement at all.,did not improvement
4,"Helped cuticles, didn't do much for my nails. I gave this product a decent time line, two jars, six months. Nails didn't improve.",helped cuticles did not much nails gave product decent time line two jars six months nails did not improve

In [13]:
df.to_csv("../data/processed/new_cleaned.csv", index=False)